Add CI - run tests using github actions.
Metta-AI/former_mettagrid pull request #5
Opened 2024-12-02 21:34 UTC by treeform

2024-12-02 23:32 UTC, daveey requested changes

2024-12-02 23:32 UTC, daveey commented on configs/a20_40x40.yaml
> +  - _self_
what does this do?

2024-12-02 23:32 UTC, daveey commented on requirements.txt
> +hydra-core>=1.3.2
should these go into setup.py?

2024-12-02 23:32 UTC, daveey commented on tests/test_metagrid.py
> +def test_performance(env, actions, duration):
let's put these in different files. test_performance.py, test_determinism.py

2024-12-02 23:32 UTC, daveey commented on tests/test_metagrid.py
> +global actions
do these need to be global? can we move these into test_performance?

2024-12-02 23:32 UTC, daveey commented on tests/test_metagrid.py
> +@hydra.main(version_base=None, config_path="../configs", config_name="a20_40x40")
i see you copied code from the perf test. that was a janky file i was manually using to test performance. for a unittest, we should simplify. we don't need to print anything. we should just run a perf test, and assert that the speed is reasonable

2024-12-02 23:35 UTC, treeform commented on configs/a20_40x40.yaml
> +  - _self_
it does nothing, but it fixes a hydra warning, for some reason hydra wants this now.

2024-12-02 23:36 UTC, treeform commented on tests/test_metagrid.py
> +def test_performance(env, actions, duration):
yes I was just using this file as a wip

2024-12-02 23:36 UTC, treeform commented on tests/test_metagrid.py
> +@hydra.main(version_base=None, config_path="../configs", config_name="a20_40x40")
thats correct I just wanted a file that had some thing running.

my plan is to write this file to be more a test thing

I mostly worked on the build.yml

2024-12-02 23:42 UTC, treeform commented on requirements.txt
> +hydra-core>=1.3.2
I had issues with hydra and other libs. I will move them to setup.py eventually.

2024-12-06 18:34 UTC, treeform commented on requirements.txt
> +hydra-core>=1.3.2
Turns out I need this to make "pufferlib" and "puffergrid" work. Once I fix setup.py in "pufferlib" and "puffergrid" requirements.txt could be removed but one thing at a time. I want to get this working.

2024-12-06 18:36 UTC, treeform commented on configs/a20_40x40.yaml
> +  - _self_
> Explicitness: The _self_ keyword makes it explicit which part of the configuration is being overridden or extended. This reduces ambiguity, especially in large and complex configurations.

2024-12-06 22:59 UTC, daveey requested changes

2024-12-06 22:59 UTC, daveey commented on setup.py
> +        "hydra-core>=1.3.2",
can you just read this from requirements.txt so we don't need 2 copies or places to edit?

2024-12-06 22:59 UTC, daveey commented on tests/test_basic.py
> +    assert mettaGridEnv.grid_features == [
every time we add a property, we're gonna have to edit this file. let's not make people do that

2024-12-06 22:59 UTC, daveey commented on tests/test_basic.py
> +    print("mettaGridEnv.global_features: ", mettaGridEnv.global_features)
i appreciate trying to have unittests, but this seems like it's just making work for people without providing much value.

2024-12-06 23:05 UTC, treeform commented on setup.py
> +        "hydra-core>=1.3.2",
The requirements.txt will go a way once "pufferlib" and "puffergrid" setup.py works. Do you want me to switch to working on those repos instead? I did not want to overcomplicate this PR, but I can do that instead.

2024-12-06 23:07 UTC, treeform commented on tests/test_basic.py
> +    assert mettaGridEnv.grid_features == [
I could remove this if you like. But I appears that actions come from test_basic.yaml. If actions get added that are not part of test_basic.yaml that should fail this test?

2024-12-06 23:09 UTC, treeform commented on tests/test_basic.py
> +    print("mettaGridEnv.global_features: ", mettaGridEnv.global_features)
I need an annoying unit test so that I make big changes to metagrid and puffergrid and make sure I break nothing. But I could see having two sets of tests one for normal use and one for big refactors.

2024-12-07 17:03 UTC, treeform commented on requirements.txt
> +hydra-core>=1.3.2
I changed my mind on this. I think requirements.txt is needed because `python setup.py build_ext --inplace` does not install any of the require libs only `python setup.py install` does. Also to run setup.py you need to have some dependancies already in place. I think its cleaner to just move all deps to requirements.txt. There are not extra copies of the deps.

2024-12-07 17:03 UTC, treeform commented on setup.py
> +        "hydra-core>=1.3.2",
I removed the two copies. There is only one copy of all requirements.

2024-12-07 17:04 UTC, treeform commented on tests/test_basic.py
> +    assert mettaGridEnv.grid_features == [
I removed this assert for now.

2024-12-07 17:04 UTC, treeform commented on tests/test_basic.py
> +    print("mettaGridEnv.global_features: ", mettaGridEnv.global_features)
I removed this assert for now.

2024-12-11 18:07 UTC, daveey approved these changes

2024-12-11 18:07 UTC, merged